version: '3.8'
services:
  jsight-server:
    build:
      context: .
    environment:
      - JSIGHT_SERVER_CORS
      - JSIGHT_SERVER_STATISTICS
    ports:
      - '${DOCKER_COMPOSE_HOST_PORT}:8080'
      