version: 2.1

orbs:
  docker: circleci/docker@2.0.3
  common: jsight/common-ci@1.3.2

parameters:
  image-tag:
    type: string
    default: ${CIRCLE_BRANCH/\//_}_${CIRCLE_SHA1}

workflows:
  release-tag:
    when:
      matches:
        pattern: "^release-.*"
        value: << pipeline.git.tag >>
    jobs:
      - docker/publish:
          filters: &release-tag-filter
            tags:
              only: /^release-.*/
          executor: common/vm-medium
          context: &common-context online-editor-development
          image: jsight/jsight-server
          tag: '${FULL_VERSION},${MAJOR_VERSION},latest' # values available thx to before_build
          before_build:
            - common/parse-versions
          extra_build_args: &docker_build_args '
            --build-arg CORS=false
            --build-arg STATISTICS=true'
      - approve-production-deploy:
          filters: *release-tag-filter
          type: approval
          requires:
            - docker/publish
      - common/refresh-container:
          filters: *release-tag-filter
          requires:
            - approve-production-deploy
          context: *common-context
          host: ${HOST_PROD}
          host-port: 8080
          container-port: 8080
          container-name: jsight-server
          image: jsight/jsight-server
          tag: latest
      - common/notify-telegram:
          filters: *release-tag-filter
          requires:
            - common/refresh-container
          context: *common-context
          message: >
            Production Server updated from tag << pipeline.git.tag >>

  rc-branch:
    when:
      matches:
        pattern: "^rc/.*"
        value: << pipeline.git.branch >>
    jobs:
      - docker/publish: &dev-publish
          executor: common/vm-medium
          context: *common-context
          image: &dev-image jsight/dev-jsight-server
          tag: '<< pipeline.parameters.image-tag >>,stage_latest'
          extra_build_args: &docker_build_args '
             --build-arg CORS=true
             --build-arg STATISTICS=true'
      - common/refresh-container: &dev-refresh
          requires:
            - docker/publish
          context: *common-context
          host: ${HOST_STAGE}
          host-port: 8080
          container-port: 8080
          container-name: jsight-server
          image: *dev-image
          tag: << pipeline.parameters.image-tag >>
      - common/notify-telegram: &dev-notify
          requires:
            - common/refresh-container
          context: *common-context
          message: Stage Server updated from branch ${CIRCLE_BRANCH} (commit ${CIRCLE_SHA1})

  dev-branch:
    when:
      equal: [ dev, << pipeline.git.branch >> ]
    jobs:
      - docker/publish:
          <<: *dev-publish
          tag: '<< pipeline.parameters.image-tag >>,dev_latest'
      - common/refresh-container:
          <<: *dev-refresh
          host: ${HOST_DEV}
      - common/notify-telegram:
          <<: *dev-notify
          message: Dev Server updated from branch ${CIRCLE_BRANCH} (commit ${CIRCLE_SHA1})
