version: 2.1

orbs:
  docker: circleci/docker@2.0.3
  common: jsight/common-ci@1.3.0

parameters:
  fire:
    description: Boolean parameter to control manual workflows. Set it to true when running from gui or api.
    type: boolean
    default: false
  host-env:
    type: enum
    default: CRAZY
    enum: [DEV, STAGE, CRAZY]
  jschema-branch:
    type: string
    default: dev
  japi-branch:
    type: string
    default: dev
  github-token:
    type: string
    default: $GITHUB_TOKEN
  statistics-enabled:
    type: boolean
    default: true
  cors-enabled:
    type: boolean
    default: true


workflows:
  release-tag:
    when:
      matches:
        pattern: "^release-.*"
        value: << pipeline.git.tag >>
    jobs:
      - docker/publish:
          filters: &release-tag-filter
            tags:
              only: /^release-.*/
          executor: common/vm-medium
          context: &common-context online-editor-development
          image: jsight/jsight-server
          tag: '${FULL_VERSION},${MAJOR_VERSION},latest' # values available thx to before_build
          before_build:
            - common/parse-versions
          extra_build_args: &docker_build_args '
            --no-cache
            --build-arg JSCHEMA_BRANCH=<< pipeline.parameters.jschema-branch >>
            --build-arg JAPI_BRANCH=<< pipeline.parameters.japi-branch >>
            --build-arg GITHUB_TOKEN=<< pipeline.parameters.github-token >>
            --build-arg CORS=<< pipeline.parameters.cors-enabled >>
            --build-arg STATISTICS=<< pipeline.parameters.statistics-enabled >>'
      - approve-production-deploy:
          filters: *release-tag-filter
          type: approval
          requires:
            - docker/publish
      - common/refresh-container:
          filters: *release-tag-filter
          requires:
            - approve-production-deploy
          context: *common-context
          host: ${HOST_PROD}
          host-port: 8080
          container-port: 8080
          container-name: jsight-server
          image: jsight/jsight-server
          tag: latest
      - common/notify-telegram:
          filters: *release-tag-filter
          requires:
            - common/refresh-container
          context: *common-context
          message: >
            Production server updated from tag << pipeline.git.tag >>
            with jschema branch << pipeline.parameters.jschema-branch >>
            and japi branch << pipeline.parameters.japi-branch >>

  custom-dev:
    when:
      equal: [ true, << pipeline.parameters.fire >> ]
    jobs:
      - docker/publish:
          context: *common-context
          executor: common/vm-medium
          image: &dev_image jsight/dev-jsight-server
          tag: &dev_tag ${DOCKER_TAG} # value available thx to pre-steps
          extra_build_args: *docker_build_args
          pre-steps: &dev-branches-pre-steps
            - common/convert-to-valid-git-tag:
                input: schema_<< pipeline.parameters.jschema-branch >>__api_<< pipeline.parameters.japi-branch >>__pipe_<< pipeline.number >>
      - common/refresh-container:
          requires:
            - docker/publish
          context: *common-context
          host: ${HOST_<< pipeline.parameters.host-env >>}
          host-port: 8080
          container-port: 8080
          container-name: jsight-server
          image: *dev_image
          tag: *dev_tag
          pre-steps: *dev-branches-pre-steps
      - common/notify-telegram:
          requires:
            - common/refresh-container
          context: *common-context
          message: >
            << pipeline.parameters.host-env >> server updated from branch << pipeline.git.branch >>
            with jschema branch << pipeline.parameters.jschema-branch >>
            and japi branch << pipeline.parameters.japi-branch >>
