version: 2.1

orbs:
  docker: circleci/docker@2.0.3
  common: jsight/common-ci@1.3.2

parameters:
  image-tag:
    type: string
    default: ${CIRCLE_BRANCH/\//_}_${CIRCLE_SHA1}

workflows:
  dev-branch:
    when:
      equal: [ dev, << pipeline.git.branch >> ]
    jobs:
      - docker/publish: &base-publish
          executor: common/vm-medium
          context: &common-context online-editor-development
          image: jsight/dev-jsight-server
          tag: '<< pipeline.parameters.image-tag >>,dev_latest'
          extra_build_args: &docker_build_args '
            --build-arg CORS=false
            --build-arg STATISTICS=true'
      - common/trigger-deployment: &base-trigger
          requires:
            - docker/publish
          context: *common-context
          project: jsight-server
          env: dev
          image: jsight/dev-jsight-server:<< pipeline.parameters.image-tag >>
          notification-message: Dev JSight-Server updated from branch ${CIRCLE_BRANCH} (commit ${CIRCLE_SHA1})
          post-steps:
            - jira/notify:
                job_type: deployment
                environment_type: testing
                environment: Test

  rc-branch:
    when:
      matches:
        pattern: "^rc/.*"
        value: << pipeline.git.branch >>
    jobs:
      - docker/publish:
          <<: *base-publish
          tag: '<< pipeline.parameters.image-tag >>,stage_latest'
      - common/trigger-deployment:
          <<: *base-trigger
          env: stage
          notification-message: Stage Jsight-Server updated from branch ${CIRCLE_BRANCH} (commit ${CIRCLE_SHA1})
          post-steps:
            - jira/notify:
                job_type: deployment
                environment_type: staging
                environment: Staging

  release-tag:
    when:
      matches:
        pattern: "^release-.*"
        value: << pipeline.git.tag >>
    jobs:
      - docker/publish:
          <<: *base-publish
          filters: &release-tag-filter
            tags:
              only: /^release-.*/
          image: jsight/jsight-server
          tag: '${FULL_VERSION},${MAJOR_VERSION},latest' # values available thx to before_build
          before_build:
            - common/parse-versions
          extra_build_args: &docker_build_args '
            --build-arg CORS=false
            --build-arg STATISTICS=true'
      - approve-production-deploy:
          filters: *release-tag-filter
          type: approval
          requires:
            - docker/publish
      - common/trigger-deployment:
          <<: *base-trigger
          filters: *release-tag-filter
          requires:
            - approve-production-deploy
          env: prod
          image: jsight/jsight-server:latest
          notification-message: Production Jsight-Server updated from tag << pipeline.git.tag >>
          post-steps:
            - jira/notify:
                job_type: deployment
                environment_type: production
                environment: Production
